language: python

python:
    - "3.6"

install:
    - pip3 install -e .
    - pip3 install pytest
    - pip3 install black

script:
    - pytest tests.py
    - black --check scalpl.py tests.py setup.py
